### ISSUE TITLE
Is this library abandoned?

### ISSUE THREAD

**Issue by enesTufekci** [algolia/search-insights.js#202]
If it is not;

I have never seen such a sloppy implementation. It is written in Typescript but types are not exposed, what?
Documentation is horrible, not even up to date. The api is not working how its documented. 
Source code is barely readable and full of garbage. There are 11 pull requests for such a small project.

Even if you had only one customer that uses this library, the job you have done is still unacceptable. This is not an open source project, this is a library that required for certain features that your customers need.

**Comment by francoischalifour** [comment]
Hi there—thanks for sharing this feedback. I personally share most of the pain points that you're mentioning.

The library is not abandoned. It has evolved over years which partly explains the current state of the codebase. We plan to invest more on it in the next quarters because the ease of integration has not been what we originally hoped for.

It's been written in TypeScript to leverage their compiler and ease the refactoring process. We initially only exported a UMD build which couldn't leverage exported types.

Regarding documentation, it would be productive to share what didn't work for you, so that we can correct it. Would you mind sharing what steps went wrong in the implementation process?

Some of the reasons we open source our frontend libraries are:

- Allow external contributors to share their feedback (which is what you're doing right now)
- Allow external contributors to improve our products (which could be done with PRs for documentation or TypeScript improvements for example)

I hope you understand!

**Comment by enesTufekci** [comment]
Hey thanks for the reply, 
Here is an example how I made it work, https://codesandbox.io/s/sharp-night-zbr30?file=/src/App.tsx

**Comment by enesTufekci** [comment]
Is there any documentation about how to use `insights` api without using this library?

**Comment by francoischalifour** [comment]
Since you use React, I would recommend creating a hook that abstracts the setup logic:

```tsx
function useInsights(appId: string, apiKey: string, userToken: string) {
  React.useEffect(() => {
    aa("init", {
      appId,
      apiKey
    });
  }, [appId, apiKey]);

  React.useEffect(() => {
    aa("setUserToken", userToken);
  }, [userToken]);

  return {
    clickedObjectIDs: (...args: any[]) => aa("clickedObjectIDs", ...args)
  };
}
```

You can find [your example modified on this sandbox](https://codesandbox.io/s/determined-shadow-3cved?file=/src/App.tsx).

If you're not satisfied with such an abstraction, you can go all the way down to [using our Insights REST API](https://www.algolia.com/doc/rest-api/insights/).

**Comment by enesTufekci** [comment]
Thank you for the example,

But I am having this warning when I use it with real credentials, is this mean something needs to be activated for these credentials in order to use this api?
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://insights.algolia.io/1/events?X-Algolia-Application-Id=V7W8#####&X-Algolia-API-Key=241fd8f389###############&X-Algolia-Agent=insights-js%20(1.4.0) with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Comment by francoischalifour** [comment]
Closing this since there's no actionable steps.
