### ISSUE TITLE
CORB is fired by Chrome when an event is requested

### ISSUE THREAD

**Issue by Haroenv** [algolia/search-insights.js#253]
The request still happens, but the response is never decoded. As far as I can tell, this is because the request mime type is `content-type: text/plain;charset=UTF-8` (although accept is `*/*`), while the response is `application/json`.

resources: https://www.chromium.org/Home/chromium-security/corb-for-developers

```
search-insights@1.7.1:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://insights.algolia.io/1/events?X-Algolia-Application-Id=B1G2GM9NG0&X-Algolia-API-Key=aadef574be1f9252bb48d4ea09b5cfe5&X-Algolia-Agent=insights-js%20(1.7.1) with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

demo: https://olkqj0ym0y.csb.app/ and click on an event-firing button. Then check the console and see this error.

Only Chrome has this feature so far.

**Comment by 619** [comment]
same!

**Comment by Haroenv** [comment]
I've checked in with the backend team, and they mentioned that this CORB is only a warning, not an actual failing request. The problem is that the backend returns an empty response with response code 200 (although it technically should be 204). Making the change to error code 204 would be a breaking change, thus it can't be changed.

Since this is a fully backend "issue", I will close it here, but if more than a warning shows up in the console, please contact support@algolia.com and mention this issue.

**Comment by ronfor** [comment]
Hi @Haroenv, please can we reopen this issue? Causing warnings for every page an event is triggered for all chromium based browsers does seem like something which needs to be resolved. Additionally because the client sends the version in the request, it appears the 204 response could be returned for specific versions of the client so that it is not a breaking change?

**Comment by eunjae-lee** [comment]
From the chromium website, they said

> Chrome will stop showing warning messages for empty or error responses in Chrome 69, since these are false positives that do not affect site behavior.

I'm on Chrome 93, and it seems they haven't removed the warning.

**Comment by Haroenv** [comment]
@eunjae-lee, can you investigate if an accept content-type can be sent?

**Comment by eunjae-lee** [comment]
@Haroenv 

> The problem is that the backend returns an empty response with response code 200 (although it technically should be 204)

Not sure if it's true. From my observation, there is a valid json response, but the initiator was sendBeacon, not XHR, so the browser decided not to display the response, which made it look empty.

https://user-images.githubusercontent.com/499898/149120294-0f02de84-9495-435d-9ee3-d770ee423e46.mp4

 I'm not seeing the warning message any more in my Chrome 97, though.

> can you investigate if an accept content-type can be sent?

not sure what you mean by that

**Comment by eunjae-lee** [comment]
I tested it again and it's happening with `navigator.sendBeacon()` only. With `XMLHttpRequest` it's fine.

```js
  navigator.sendBeacon('https://insights.algolia.io/1/events?X-Algolia-Application-Id=B1G2GM9NG0&X-Algolia-API-Key=aadef574be1f9252bb48d4ea09b5cfe5&X-Algolia-Agent=insights-js%20(1.7.1)%3B%20insights-middleware'
    ,'{"events":[{"eventType":"click","eventName":"my-click-event","userToken":"anonymous-f34a0761-3ebe-4e75-835c-aa1d943d998b","index":"demo_ecommerce","queryID":"3cd8f8dcf2637b757b23d577b31844e3","objectIDs":["131280270"],"positions":[1]}]}'
  );
```

Running the code above at https://olkqj0ym0y.csb.app/ triggers the warning. 

CORB is to validate response for security purpose, but in case of beacon, there is no response by design. I suspect it may be a bug in the browser implementation.

Anyway I tried the following to see what we can do to remove the warning.

```js
url = 'https://insights.algolia.io/1/events?X-Algolia-Application-Id=B1G2GM9NG0&X-Algolia-API-Key=aadef574be1f9252bb48d4ea09b5cfe5&X-Algolia-Agent=insights-js%20(1.7.1)%3B%20insights-middleware'

body = '{"events":[{"eventType":"click","eventName":"my-click-event","userToken":"anonymous-f34a0761-3ebe-4e75-835c-aa1d943d998b","index":"demo_ecommerce","queryID":"3cd8f8dcf2637b757b23d577b31844e3","objectIDs":["131280270"],"positions":[1]}]}'

headers = {
    accept: 'application/json',
    'content-type': 'application/json'
  };
blob = new Blob([body], headers);

navigator.sendBeacon(url, blob)
```

But it didn't affect accept or content-type headers in the request.

**Comment by igbominadeveloper** [comment]
So what is the solution to this problem right now? My events are not getting sent to Algolia

**Comment by Haroenv** [comment]
@igbominadeveloper, are you sure the events aren't sent? sendbeacon does not show up in the regular "xhr/fetch" tab in the network panel, but in the "other" or "beacon" tabs.

Do you have a reproduction where more than a warning, the request doesn't happen?

**Comment by Finesse** [comment]
> this is because the request mime type is `content-type: text/plain;charset=UTF-8`

`Content-Type` request header has nothing to do with the response, it only tells the content type of the request body. `Accept` is designed to affect the response type, but it is not related to the warning too.

The warning is caused by [the CORB feature](https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md#Protecting-JSON). In a nutshell, Chrome protects cross-origin JSON responses by allowing them to be read only by `fetch` and `XMLHttpRequest`. `navigator.sendBeacon` is not in this list, so the warning is produced. I personally think it makes no sense because `navigator.sendBeacon` doesn't return the response to JavaScript anyway.

To fix this, the server must return a response which body doesn't looks like JSON. The response must look like neither XML nor HTML too. `Access-Control-Allow-*` headers won't help. You can use https://webhook.site/ to play with different responses (click the "Edit" butotn).

**Comment by Finesse** [comment]
This Chrome bug is acknowledged by Google but not fixed yet: https://bugs.chromium.org/p/chromium/issues/detail?id=1007155

**Comment by Antonytm** [comment]
The bug is still in place.
