### ISSUE TITLE
How to integrate with requirejs

### ISSUE THREAD

**Issue by vivek-yes** [algolia/search-insights.js#6]
I wanted to know how to import the click analytics library (search-insight library) to the page using requirejs.

**Comment by Haroenv** [comment]
Hey @vivek-yes, this is definitely possible since it's distributed as a UMD:

https://cdn.jsdelivr.net/npm/search-insights@0.0.14/dist/search-insights.min.js

Using regular requirejs you'd download this file somewhere in your project and link to it relatively, but you can also use the cdn link. 

Could you let me know where you're having problems?

**Comment by vivek-yes** [comment]
Thanks for the prompt reply !!!!
Basically i wanted to implement the first step in this page using requirejs
https://www.algolia.com/doc/tutorials/getting-started/how-to-implement-analytics/#introduction

**Comment by Haroenv** [comment]
Should be possible like this:

```js
requirejs(['https://cdn.jsdelivr.net/npm/search-insights@0.0.14'], function(aa) {
// whatever
});
```

Note that the way we wrote it has a fallback for events before the library loads, so it's still recommended to do it as in the documentation. Please reopen if this didn't work @vivek-yes
